### ISSUE TITLE
CEP não autocompleta

### ISSUE THREAD

**Issue by vipracingshopping** [deivisonarthur/OSC-Magento-Brasil-6-Pro#282]
Li muitas Issues aqui e não sei se o pessoal ta tendo o mesmo retorno que eu

O CEP não auto completa para novos endereços, mas o frete é calculado sem problemas

veja meu console:

    Uncaught TypeError: Cannot read property 'style' of null                         prototype.js:1931
    at Function.hide (https://www.vipracingshopping.com.br/js/prototype/prototype.js:1931:12)
    at klass.baseInitialize (https://www.vipracingshopping.com.br/js/scriptaculous/controls.js:88:13)
    at klass.initialize (https://www.vipracingshopping.com.br/js/scriptaculous/controls.js:347:10)
    at new klass (https://www.vipracingshopping.com.br/js/prototype/prototype.js:101:23)
    at klass.initAutocomplete (https://www.vipracingshopping.com.br/js/varien/js.js:340:9)
    at https://www.vipracingshopping.com.br/onestepcheckout/index/:322:16

Magento 1.7.0.2
Soap OK
Magento check OK

**Comment by apzeiro** [comment]
Estou percebendo o mesmo problema. Quando seleciona NOVO ENDEREÇO no ckeckout fica carregando eternamente. Aqui até autocompleta depois de um tempão, mas as telas de frete e total fica só girando.

**Comment by hansbonini** [comment]
Aplique o patch do pull request #268

**Comment by apzeiro** [comment]
@hansbonini Vou testar. Valeu!

**Comment by FelipeMartinin** [comment]
@apzeiro Eai, rolou?

**Comment by apzeiro** [comment]
@FelipeMartinin ronou nada.
Não deu certo ainda.
