### ISSUE TITLE
Olá Estou tendo erro de conflito com o modulo antigo o 4

### ISSUE THREAD

**Issue by jefter** [deivisonarthur/OSC-Magento-Brasil-6-Pro#70]
Error in file: "/home/botan965/public_html/app/code/community/Inovarti/Onestepcheckout/sql/onestepcheckout_setup/mysql4-install-2.0.0.php" - SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-ie' for key 'UNQ_EAV_ATTRIBUTE_ENTITY_TYPE_ID_ATTRIBUTE_CODE'

Trace:
#0 /home/botan965/public_html/app/code/core/Mage/Core/Model/Resource/Setup.php(645): Mage::exception('Mage_Core', 'Error in file: ...')
#1 /home/botan965/public_html/app/code/core/Mage/Core/Model/Resource/Setup.php(421): Mage_Core_Model_Resource_Setup->_modifyResourceDb('install', '', '2.0.2')
#2 /home/botan965/public_html/app/code/core/Mage/Core/Model/Resource/Setup.php(327): Mage_Core_Model_Resource_Setup->_installResourceDb('2.0.2')
#3 /home/botan965/public_html/app/code/core/Mage/Core/Model/Resource/Setup.php(235): Mage_Core_Model_Resource_Setup->applyUpdates()
#4 /home/botan965/public_html/app/code/core/Mage/Core/Model/App.php(417): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#5 /home/botan965/public_html/app/code/core/Mage/Core/Model/App.php(343): Mage_Core_Model_App->_initModules()
#6 /home/botan965/public_html/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#7 /home/botan965/public_html/index.php(87): Mage::run('', 'store')
#8 {main}

**Comment by rafaelstz** [comment]
Tenta remover o xml do antigo na pasta **app/etc/modules** e remover o registro dos dois na tabela **core_resource**

**Comment by jefter** [comment]
Eu removi o xml antigo, deletei o registro referente ao OSC ta tabela core_resource, reindexei, limpei o cache, mas ai joguei os arquivos no FTP na pasta raiz e quando atualizei o magento deu erro.

Eu foi no xml deixe o active com false, dai volta ao normal, depois fui no admin > configuração > avançado e aparece para mim o modulo inovarti_Onestepcheckout

**Comment by rafaelstz** [comment]
Ele ativo não aparece no front e no back?

**Comment by jefter** [comment]
Quando eu ativo tanto no front ou no back aparece esse erro

Error in file: "/home/botan965/public_html/app/code/community/Inovarti/Onestepcheckout/sql/onestepcheckout_setup/mysql4-install-2.0.0.php" - SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-ie' for key 'UNQ_EAV_ATTRIBUTE_ENTITY_TYPE_ID_ATTRIBUTE_CODE'

Trace:
#0 /home/botan965/public_html/app/code/core/Mage/Core/Model/Resource/Setup.php(645): Mage::exception('Mage_Core', 'Error in file: ...')
#1 /home/botan965/public_html/app/code/core/Mage/Core/Model/Resource/Setup.php(421): Mage_Core_Model_Resource_Setup->_modifyResourceDb('install', '', '2.0.2')
#2 /home/botan965/public_html/app/code/core/Mage/Core/Model/Resource/Setup.php(327): Mage_Core_Model_Resource_Setup->_installResourceDb('2.0.2')
#3 /home/botan965/public_html/app/code/core/Mage/Core/Model/Resource/Setup.php(235): Mage_Core_Model_Resource_Setup->applyUpdates()
#4 /home/botan965/public_html/app/code/core/Mage/Core/Model/App.php(417): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#5 /home/botan965/public_html/app/code/core/Mage/Core/Model/App.php(343): Mage_Core_Model_App->_initModules()
#6 /home/botan965/public_html/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#7 /home/botan965/public_html/index.php(87): Mage::run('', 'store')
#8 {main}


Desde já agradeço pela atenção!
