### ISSUE TITLE
Erro após desinstalar

### ISSUE THREAD

**Issue by fabiolopeschaves** [deivisonarthur/OSC-Magento-Brasil-6-Pro#79]
Após desinstalar o módulo , tenho tido alguns erros no site. Não é possível fechar pedido quando o cliente está logado ( na página de checkout padrão do magento, após as Informações de Cobrança, ao clicar em continuar ele me da a mensagem de erro Informe o estado )

Alguns pedidos não abrem e quando clicado em algum cliente também da erro.
Segue o report

a:5:{i:0;s:111:"Modelo base "idecheckoutvm/customer_attribute_source_pessoa_view" não encontrado para o atributo "tipo_pessoa"";i:1;s:5634:"#0 /home/brcaps/public_html/app/code/core/Mage/Eav/Model/Entity/Attribute/Abstract.php(387): Mage::exception('Mage_Eav', 'Modelo base "id...')
#1 /home/brcaps/public_html/app/code/core/Mage/Eav/Model/Attribute/Data/Select.php(114): Mage_Eav_Model_Entity_Attribute_Abstract->getSource()
#2 /home/brcaps/public_html/app/code/core/Mage/Eav/Model/Attribute/Data/Select.php(131): Mage_Eav_Model_Attribute_Data_Select->_getOptionText('F')
#3 /home/brcaps/public_html/app/code/core/Mage/Adminhtml/Block/Sales/Order/View/Info.php(134): Mage_Eav_Model_Attribute_Data_Select->outputValue('html')
#4 /home/brcaps/public_html/app/design/adminhtml/default/default/template/sales/order/view/info.phtml(136): Mage_Adminhtml_Block_Sales_Order_View_Info->getCustomerAccountData()
#5 /home/brcaps/public_html/app/code/core/Mage/Core/Block/Template.php(241): include('/home/brcaps/pu...')
#6 /home/brcaps/public_html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#7 /home/brcaps/public_html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#8 /home/brcaps/public_html/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#9 /home/brcaps/public_html/app/code/core/Mage/Core/Block/Abstract.php(863): Mage_Adminhtml_Block_Template->_toHtml()
#10 /home/brcaps/public_html/app/code/core/Mage/Core/Block/Abstract.php(582): Mage_Core_Block_Abstract->toHtml()
#11 /home/brcaps/public_html/app/code/core/Mage/Core/Block/Abstract.php(526): Mage_Core_Block_Abstract->_getChildHtml('order_info', true)
#12 /home/brcaps/public_html/app/design/adminhtml/default/default/template/sales/order/view/tab/info.phtml(33): Mage_Core_Block_Abstract->getChildHtml('order_info')
#13 /home/brcaps/public_html/app/code/core/Mage/Core/Block/Template.php(241): include('/home/brcaps/pu...')
#14 /home/brcaps/public_html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#15 /home/brcaps/public_html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#16 /home/brcaps/public_html/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#17 /home/brcaps/public_html/app/code/core/Mage/Core/Block/Abstract.php(863): Mage_Adminhtml_Block_Template->_toHtml()
#18 /home/brcaps/public_html/app/code/core/Mage/Adminhtml/Block/Widget/Tabs.php(303): Mage_Core_Block_Abstract->toHtml()
#19 /home/brcaps/public_html/app/design/adminhtml/default/default/template/widget/tabs.phtml(38): Mage_Adminhtml_Block_Widget_Tabs->getTabContent(Object(Mage_Adminhtml_Block_Sales_Order_View_Tab_Info))
#20 /home/brcaps/public_html/app/code/core/Mage/Core/Block/Template.php(241): include('/home/brcaps/pu...')
#21 /home/brcaps/public_html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#22 /home/brcaps/public_html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#23 /home/brcaps/public_html/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#24 /home/brcaps/public_html/app/code/core/Mage/Core/Block/Abstract.php(863): Mage_Adminhtml_Block_Template->_toHtml()
#25 /home/brcaps/public_html/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#26 /home/brcaps/public_html/app/code/core/Mage/Core/Block/Abstract.php(863): Mage_Core_Block_Text_List->_toHtml()
#27 /home/brcaps/public_html/app/code/core/Mage/Core/Block/Abstract.php(582): Mage_Core_Block_Abstract->toHtml()
#28 /home/brcaps/public_html/app/code/core/Mage/Core/Block/Abstract.php(526): Mage_Core_Block_Abstract->_getChildHtml('left', true)
#29 /home/brcaps/public_html/app/design/adminhtml/default/default/template/page.phtml(58): Mage_Core_Block_Abstract->getChildHtml('left')
#30 /home/brcaps/public_html/app/code/core/Mage/Core/Block/Template.php(241): include('/home/brcaps/pu...')
#31 /home/brcaps/public_html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#32 /home/brcaps/public_html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#33 /home/brcaps/public_html/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#34 /home/brcaps/public_html/app/code/core/Mage/Core/Block/Abstract.php(863): Mage_Adminhtml_Block_Template->_toHtml()
#35 /home/brcaps/public_html/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#36 /home/brcaps/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#37 /home/brcaps/public_html/app/code/core/Mage/Adminhtml/controllers/Sales/OrderController.php(119): Mage_Core_Controller_Varien_Action->renderLayout()
#38 /home/brcaps/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(419): Mage_Adminhtml_Sales_OrderController->viewAction()
#39 /home/brcaps/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('view')
#40 /home/brcaps/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#41 /home/brcaps/public_html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#42 /home/brcaps/public_html/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#43 /home/brcaps/public_html/index.php(88): Mage::run('', 'store')
#44 {main}";s:3:"url";s:86:"/index.php/admin/sales_order/view/order_id/1233/key/d3f9f2094da513ddf29e09f43c48557e/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}

**Comment by fabiolopeschaves** [comment]
Alguém ?

**Comment by FabioSee** [comment]
Esse erro vai acontecer pq provavelmente o pedido foi fechado naquela modalidade de pagamento que desinstalou... ou seja aquele pedido foi fechado naquele modelo e agora ele nao tem mais os campos, dados etc para listar..
Olhe a primeira linha do seu erro... tipo_pessoa... no checkout normal do magento nao existe tipo_pessoa.... por isso vai dar erro ao listar aquele pedido especifico.

**Comment by isaaclopes** [comment]
@fabiolopeschaves acredito que não seja a OSC6 pois o erro que esta dando não é desse modulo, é no 
modulo "idecheckoutvm".
a:5:{i:0;s:111:"Modelo base "idecheckoutvm/customer_attribute_source_pessoa_view" não encontrado para o atributo "tipo_pessoa"";i:1;s:5634:"#0  e o campo é "tipo_pessoa"  não existe esse campo na OSC6 e sim o tipopessoa tudo junto. 

segue setup dos campos
https://github.com/deivisonarthur/OSC-Magento-Brasil-6-Pro/blob/master/app/code/community/Inovarti/Onestepcheckout/sql/onestepcheckout_setup/mysql4-install-2.0.0.php

da uma olhada no arquivo /home/brcaps/public_html/app/design/adminhtml/default/default/template/sales/order/view/info.phtml
linha (136) se ele não chama o campo que esta com erro.
