### ISSUE TITLE
OCS 6 - Problemas na tela de Cadastro e Checkout

### ISSUE THREAD

**Issue by emersonramos** [deivisonarthur/OSC-Magento-Brasil-6-Pro#96]
Bom dia a todos,

Instalei a versão 6 do OCS e tive um problema estranho.

Na tela de criação de Cadastro, ele exibe o campo CPF. Após este campo não tem mais nada, inclusive o botão para concluir o Cadastro.

Na tela de Checkout, se o usuário não estiver logado, ele exibe apenas a primeira coluna do cadastro e, coincidentemente, me parece q para de exibir justamente após o campo de CPF. Se eu estiver logado, a página de Checkout abre normalmente.

Alguém já passou por isso?

**Comment by rafaelstz** [comment]
Há algum erro de sintaxe nesse trecho impossibilitando a renderização do restante da página após o erro.

**Comment by emersonramos** [comment]
Eu habilitei o log do Magento, mas não apresenta nada.

Eu não sou programador, postei na esperança de alguém ter passado por algo semelhante.

**Comment by emersonramos** [comment]
Consegui pegar esse log. Alguém consegue me ajudar com essas informações?

exception 'Mage_Core_Exception' with message 'Tipo de bloco inválido: Inovarti_Onestepcheckout_Block_Widget_Ie' in /chroot/home/../html/app/Mage.php:595
Stack trace:
#0 /chroot/home/../html/includes/src/__default.php(28016): Mage::throwException('Tipo de bloco i...')
#1 /chroot/home/../html/includes/src/__default.php(27958): Mage_Core_Model_Layout->_getBlockInstance('onestepcheckout...', Array)
#2 /chroot/home/../html/app/design/frontend/base/default/template/onestepcheckout/persistent/customer/form/register.phtml(160): Mage_Core_Model_Layout->createBlock('onestepcheckout...')
#3 /chroot/home/../html/includes/src/__default.php(3387): include('/chroot/home/um...')
#4 /chroot/home/../html/includes/src/__default.php(3418): Mage_Core_Block_Template->fetchView('frontend/base/d...')
#5 /chroot/home/../html/includes/src/__default.php(3432): Mage_Core_Block_Template->renderView()
#6 /chroot/home/../html/includes/src/__default.php(2592): Mage_Core_Block_Template->_toHtml()
#7 /chroot/home/../html/includes/src/__default.php(13594): Mage_Core_Block_Abstract->toHtml()
#8 /chroot/home/../html/includes/src/__default.php(2592): Mage_Core_Block_Text_List->_toHtml()
#9 /chroot/home/../html/includes/src/__default.php(2310): Mage_Core_Block_Abstract->toHtml()
#10 /chroot/home/../html/includes/src/__default.php(2254): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#11 /chroot/home/../html/app/design/frontend/ultimo/default/template/page/1column.phtml(53): Mage_Core_Block_Abstract->getChildHtml('content')
#12 /chroot/home/../html/includes/src/__default.php(3387): include('/chroot/home/um...')
#13 /chroot/home/../html/includes/src/__default.php(3418): Mage_Core_Block_Template->fetchView('frontend/ultimo...')
#14 /chroot/home/../html/includes/src/__default.php(3432): Mage_Core_Block_Template->renderView()
#15 /chroot/home/../html/includes/src/__default.php(2592): Mage_Core_Block_Template->_toHtml()
#16 /chroot/home/../html/includes/src/__default.php(28076): Mage_Core_Block_Abstract->toHtml()
#17 /chroot/home/../html/includes/src/__default.php(13987): Mage_Core_Model_Layout->getOutput()
#18 /chroot/home/../html/app/code/core/Mage/Customer/controllers/AccountController.php(258): Mage_Core_Controller_Varien_Action->renderLayout()
#19 /chroot/home/../html/includes/src/__default.php(14015): Mage_Customer_AccountController->createAction()
#20 /chroot/home/../html/includes/src/__default.php(18399): Mage_Core_Controller_Varien_Action->dispatch('create')
#21 /chroot/home/../html/includes/src/__default.php(17933): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#22 /chroot/home/../html/includes/src/__default.php(20705): Mage_Core_Controller_Varien_Front->dispatch()
#23 /chroot/home/../html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#24 /chroot/home/../html/index.php(87): Mage::run('', 'store')
#25 {main}

**Comment by emersonramos** [comment]
Boa noite,

Descobri o trecho que está apresentando problema no arquivo register.phtml do módulo. O trecho é:

<?php $_ie = $this->getLayout()->createBlock('onestepcheckout/widget_ie') ?>
                <?php if ($_ie->isEnabled()): ?>
                    <li class="wide">
                        <?php echo $_ie->setDate($this->getFormData()->getIe())->toHtml() ?>
                    </li>
                <?php endif ?>

Quando comentei esse trecho, a página carregou normalmente. Alguém pode me dar uma luz pq este bloco não está carregando?
